### ISSUE TITLE
dataset.py requires missing npy

### ISSUE THREAD

**Issue by fanchenyou** [Cram3r95/mapfe4mp#1]
Hi folks, 
I followed your README and ran the default ``python train.py --trainer mapfe4mp --device_gpu 0"
The first time, error reports not found preprocessed data.

Then I modified config_mapfe4mp.yml  to enable preprocess_data and save_data.

Then I run again  but encountered the issue that missing 
arget_agent_orientation.npy
oracle_centerlines.npy
relevant_centerlines.npy
during preprocessing.

This breaks data_utils.py function load_processed_files_from_npy, as required_variables_name_list not all satisfied.
 I wonder how to perform preprocessing properly?
thank you.

**Comment by Cram3r95** [comment]
Hi @fanchenyou, I am working on unifying some files and fixing some bugs. They will be solved by the end of June, since this month Im finishing my PhD. Just wait a little bit. These files should actually be a single .pkl file, it was my fault in my first algorithms to store each individual np.array as a different .npy file.

Nevertheless, maybe you have correctly preprocessed the target agent orientation, oracle centerlines and relevant centerlines, but you have not renamed them properly. I should add this to the repo.

**Comment by fanchenyou** [comment]
Sure. Best wish to your thesis defense.

**Comment by librlike** [comment]
> Hi folks, I followed your README and ran the default ``python train.py --trainer mapfe4mp --device_gpu 0" The first time, error reports not found preprocessed data.
> 
> Then I modified config_mapfe4mp.yml to enable preprocess_data and save_data.
> 
> Then I run again but encountered the issue that missing arget_agent_orientation.npy oracle_centerlines.npy relevant_centerlines.npy during preprocessing.
> 
> This breaks data_utils.py function load_processed_files_from_npy, as required_variables_name_list not all satisfied. I wonder how to perform preprocessing properly? thank you.

Hi，Have you successfully reproduced it?

**Comment by fanchenyou** [comment]
Hi, It's a bit of hard but possible to make it run. I will close this comment. Thanks.

**Comment by Cram3r95** [comment]
Hi, i am working on It @librlike, It will be done the next week, as well as the repository of argo2.

**Comment by fanchenyou** [comment]
That will be great !
